import Image from 'next/image';
import styles from './singlePost.module.css'

const SinglePostPage = () => {
    return (
        <div className={styles.singlePostPageContainer}>
            <div className={styles.imgContainer}></div>
            <div className={styles.postContainer}>
                <h1 className={styles.title}>This is a random title that I made up.</h1>
                <div className={styles.date}>01-09-2024</div>
                <div className={styles.content}>
                    <img className={styles.img} src="/../img/catphoto.jpg" alt='cat photo'/>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus turpis in eu. Gravida cum sociis natoque penatibus et. Viverra accumsan in nisl nisi scelerisque eu. Et odio pellentesque diam volutpat. Nulla aliquet enim tortor at auctor urna nunc id. Iaculis nunc sed augue lacus. Amet dictum sit amet justo donec enim. Eget nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. At risus viverra adipiscing at.</p>
                    <p>Quisque id diam vel quam elementum. In tellus integer feugiat scelerisque varius morbi enim nunc. Quisque sagittis purus sit amet volutpat consequat mauris nunc. In hac habitasse platea dictumst quisque. Lectus sit amet est placerat in. Ultricies lacus sed turpis tincidunt id. Mauris pharetra et ultrices neque. Adipiscing diam donec adipiscing tristique risus nec. Lobortis scelerisque fermentum dui faucibus in ornare. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis massa sed elementum tempus egestas sed sed. Duis tristique sollicitudin nibh sit amet. Duis convallis convallis tellus id interdum velit laoreet id donec. Imperdiet massa tincidunt nunc pulvinar sapien et ligula. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Nullam vehicula ipsum a arcu cursus vitae. Eu scelerisque felis imperdiet proin fermentum. Pretium aenean pharetra magna ac placerat vestibulum. At in tellus integer feugiat scelerisque varius.</p>
                    <p>Dignissim suspendisse in est ante in. Enim nec dui nunc mattis enim. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tristique risus nec feugiat in fermentum posuere. Nunc non blandit massa enim nec dui nunc mattis. Pellentesque dignissim enim sit amet venenatis. Praesent semper feugiat nibh sed pulvinar proin gravida. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Consectetur libero id faucibus nisl tincidunt. Imperdiet dui accumsan sit amet nulla facilisi. Tellus pellentesque eu tincidunt tortor. Lectus proin nibh nisl condimentum. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium.</p>
                    <p>Imperdiet nulla malesuada pellentesque elit. Purus sit amet luctus venenatis lectus magna fringilla urna. Cursus eget nunc scelerisque viverra. Vitae sapien pellentesque habitant morbi tristique. Nulla facilisi cras fermentum odio eu feugiat pretium nibh. Porta non pulvinar neque laoreet. Quis imperdiet massa tincidunt nunc pulvinar sapien. Morbi tincidunt augue interdum velit euismod in. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Volutpat odio facilisis mauris sit amet massa. Iaculis urna id volutpat lacus. Faucibus purus in massa tempor.</p>
                    <p>Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Tempor orci eu lobortis elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames. Non tellus orci ac auctor augue mauris augue. Diam vel quam elementum pulvinar etiam non. Massa tincidunt nunc pulvinar sapien. Sed velit dignissim sodales ut. In mollis nunc sed id semper risus in. Viverra orci sagittis eu volutpat odio facilisis mauris. Volutpat blandit aliquam etiam erat velit scelerisque in. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Ullamcorper morbi tincidunt ornare massa eget egestas purus. Congue eu consequat ac felis. Diam sollicitudin tempor id eu nisl nunc. Morbi quis commodo odio aenean. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Tincidunt id aliquet risus feugiat in ante metus dictum at. A scelerisque purus semper eget duis at tellus at urna.</p>
                    <p>Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Tempor orci eu lobortis elementum nibh tellus molestie nunc non. Habitant morbi tristique senectus et netus et malesuada fames. Non tellus orci ac auctor augue mauris augue. Diam vel quam elementum pulvinar etiam non. Massa tincidunt nunc pulvinar sapien. Sed velit dignissim sodales ut. In mollis nunc sed id semper risus in. Viverra orci sagittis eu volutpat odio facilisis mauris. Volutpat blandit aliquam etiam erat velit scelerisque in. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Ullamcorper morbi tincidunt ornare massa eget egestas purus. Congue eu consequat ac felis. Diam sollicitudin tempor id eu nisl nunc. Morbi quis commodo odio aenean. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Tincidunt id aliquet risus feugiat in ante metus dictum at. A scelerisque purus semper eget duis at tellus at urna.</p>
                </div>
            </div>
        </div>
    )
}

export default SinglePostPage